# Generated by Django 5.2.7 on 2026-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ENROLLED', max_length=20),
        ),
    ]
