# Generated by Django 5.2.7 on 2025-12-16 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_drop_exam_url_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assign_to_all',
            field=models.BooleanField(default=True, help_text='If False, only students in ExamAssignment can take the exam.'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('server_deadline', models.DateTimeField(help_text='Server-calculated deadline based on duration')),
                ('cheating_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TERMINATED', 'Terminated')], default='IN_PROGRESS', max_length=20)),
                ('saved_answers', models.JSONField(blank=True, default=list, help_text='Auto-saved answers')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('BLUR', 'Window Blur'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('COPY_PASTE', 'Copy/Paste Attempt')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='assessments.examsession')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='assessments.examsession'),
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at',),
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
