# Generated by Django 5.2.7 on 2025-10-08 20:35

import apps.documents.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'png', 'jpg'])])),
                ('access_level', models.CharField(choices=[('PRIVATE', 'Private'), ('DEPARTMENT', 'Department'), ('INSTITUTION', 'Institution')], default='PRIVATE', max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-accessed_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
