# Generated by Django 5.2.9 on 2025-12-18 05:23

import apps.proctoring.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_add_exam_session_and_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('snapshot_interval_seconds', models.PositiveIntegerField(default=15, help_text='How often to capture snapshots (in seconds)')),
                ('max_violations_before_terminate', models.PositiveIntegerField(default=5, help_text='Auto-terminate exam after this many violations')),
                ('detect_no_face', models.BooleanField(default=True)),
                ('detect_multiple_faces', models.BooleanField(default=True)),
                ('detect_looking_away', models.BooleanField(default=False)),
                ('require_face_verification', models.BooleanField(default=False, help_text="Verify face matches student's registered photo")),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_settings', to='assessments.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.proctoring.models.proctoring_snapshot_upload_to)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_result', models.JSONField(blank=True, default=dict, help_text='AI analysis results: {faces_detected, looking_away, confidence, etc.}')),
                ('faces_detected', models.PositiveIntegerField(default=0)),
                ('is_violation', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_snapshots', to='assessments.examsession')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('NO_FACE', 'No face detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('LOOKING_AWAY', 'Looking away from screen'), ('FACE_NOT_MATCHED', 'Face does not match registered student'), ('OBJECT_DETECTED', 'Suspicious object detected (phone, etc.)')], max_length=30)),
                ('severity', models.PositiveIntegerField(default=1, help_text='Severity level 1-5')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether the student acknowledged this violation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_violations', to='assessments.examsession')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='proctoring.proctoringsnapshot')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
    ]
