# Generated by Django 5.2.9 on 2025-12-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsettings',
            name='detect_objects',
            field=models.BooleanField(default=True, help_text='Detect phones, books, and other prohibited objects'),
        ),
        migrations.AlterField(
            model_name='proctoringsettings',
            name='detect_looking_away',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('NO_FACE', 'No face detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('LOOKING_AWAY', 'Looking away from screen'), ('FACE_NOT_MATCHED', 'Face does not match registered student'), ('OBJECT_DETECTED', 'Suspicious object detected'), ('PHONE_DETECTED', 'Phone detected in frame'), ('BOOK_DETECTED', 'Book or notes detected in frame'), ('LAPTOP_DETECTED', 'Secondary device detected'), ('PERSON_LEFT', 'Person left the frame')], max_length=30),
        ),
    ]
