# Generated by Django 5.2.9 on 2025-12-30 07:02

import apps.proctoring.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_add_exam_session_and_assignment'),
        ('proctoring', '0002_proctoringsettings_detect_objects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.proctoring.models.face_reference_upload_to)),
                ('face_encoding', models.BinaryField(blank=True, help_text='Serialized numpy array of face encoding (128-dim vector)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the active reference for the student')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quality_score', models.FloatField(default=0.0, help_text='Quality score of the face image (0-1)')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='enable_temporal_analysis',
            field=models.BooleanField(default=True, help_text='Detect patterns across multiple snapshots'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='face_verification_interval',
            field=models.PositiveIntegerField(default=30, help_text='How often to verify face (in seconds, 0 = every snapshot)'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='min_confidence_threshold',
            field=models.FloatField(default=0.6, help_text='Minimum confidence to flag a violation (0-1)'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='motion_threshold',
            field=models.PositiveIntegerField(default=30, help_text='Motion threshold to trigger extra capture (0-100)'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='temporal_window_size',
            field=models.PositiveIntegerField(default=10, help_text='Number of snapshots to analyze for patterns'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='use_confidence_scoring',
            field=models.BooleanField(default=True, help_text='Filter low-confidence violations to reduce false positives'),
        ),
        migrations.AddField(
            model_name='proctoringsettings',
            name='use_motion_detection',
            field=models.BooleanField(default=True, help_text='Capture extra snapshots on significant motion'),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='face_verification_confidence',
            field=models.FloatField(default=0.0, help_text='Face verification confidence (0-1)'),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='face_verified',
            field=models.BooleanField(default=True, help_text='Whether face matches registered student'),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='gaze_direction',
            field=models.CharField(default='unknown', help_text='Detected gaze direction: center, left, right, up, down', max_length=20),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='gaze_pitch',
            field=models.FloatField(default=0.0, help_text='Vertical gaze angle in degrees'),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='gaze_yaw',
            field=models.FloatField(default=0.0, help_text='Horizontal gaze angle in degrees'),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='motion_score',
            field=models.FloatField(default=0.0, help_text='Motion score compared to previous frame (0-100)'),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='confidence_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of confidence factors'),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='confidence_score',
            field=models.FloatField(default=1.0, help_text='AI confidence in this violation (0-1)'),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='is_false_positive',
            field=models.BooleanField(default=False, help_text='Marked as false positive after teacher review'),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proctoringsettings',
            name='max_violations_before_terminate',
            field=models.PositiveIntegerField(default=10, help_text='Auto-terminate exam after this many violations'),
        ),
        migrations.AlterField(
            model_name='proctoringsettings',
            name='require_face_verification',
            field=models.BooleanField(default=True, help_text="Verify face matches student's registered photo"),
        ),
        migrations.AlterField(
            model_name='proctoringsettings',
            name='snapshot_interval_seconds',
            field=models.PositiveIntegerField(default=5, help_text='How often to capture snapshots (in seconds)'),
        ),
        migrations.AlterField(
            model_name='proctoringsnapshot',
            name='analysis_result',
            field=models.JSONField(blank=True, default=dict, help_text='AI analysis results: {faces_detected, gaze_result, objects, etc.}'),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('NO_FACE', 'No face detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('LOOKING_AWAY', 'Looking away from screen'), ('FACE_NOT_MATCHED', 'Face does not match registered student'), ('OBJECT_DETECTED', 'Suspicious object detected'), ('PHONE_DETECTED', 'Phone detected in frame'), ('BOOK_DETECTED', 'Book or notes detected in frame'), ('LAPTOP_DETECTED', 'Secondary device detected'), ('PERSON_LEFT', 'Person left the frame'), ('INTERMITTENT_FACE', 'Face frequently disappearing'), ('PERSISTENT_GAZE_AWAY', 'Consistently looking away'), ('MULTIPLE_PERSONS_PATTERN', 'Multiple people detected over time'), ('IDENTITY_MISMATCH_PATTERN', 'Repeated face verification failures')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='proctoringsnapshot',
            index=models.Index(fields=['session', '-captured_at'], name='proctoring__session_9a6df9_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringsnapshot',
            index=models.Index(fields=['is_violation'], name='proctoring__is_viol_7736ba_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['session', '-occurred_at'], name='proctoring__session_8b8f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['violation_type'], name='proctoring__violati_5404f9_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['is_false_positive'], name='proctoring__is_fals_c663a2_idx'),
        ),
        migrations.AddField(
            model_name='studentfacereference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentfacereference',
            index=models.Index(fields=['student', 'is_active'], name='proctoring__student_7a1282_idx'),
        ),
    ]
