# Generated by Django 5.2.7 on 2026-01-23 03:28

import apps.proctoring.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_add_exam_session_and_assignment'),
        ('proctoring', '0003_enhanced_genai_proctoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.proctoring.models.session_recording_upload_to)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the recording in seconds')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('chunks_received', models.PositiveIntegerField(default=0, help_text='Number of video chunks received')),
                ('total_chunks', models.PositiveIntegerField(default=0, help_text='Expected total number of chunks')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if upload failed')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='assessments.examsession')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['session'], name='proctoring__session_1f7667_idx'), models.Index(fields=['upload_status'], name='proctoring__upload__e6dca0_idx')],
            },
        ),
    ]
